controller_list:
  - name: "position_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - tower_joint
      - arm_base_joint
      - arm_first_joint
      - arm_second_joint
      - hand_joint