sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /kinect/depth_registered/points
   filtered_cloud_topic: output_cloud
   max_range: 5.0
   padding_offset: 0.01
   padding_scale: 1
   point_subsample: 1
   frame_subsample: 1